# Generated by Django 3.1.3 on 2020-12-13 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload', models.ImageField(upload_to='contribute/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(blank=True, help_text='Alphanumeric only', max_length=255, verbose_name='Event Name')),
                ('eventDesc', models.TextField(blank=True, help_text='Description of the event', max_length=1024, null=True, verbose_name='Event Description')),
                ('fromDate', models.DateTimeField(help_text='MM/DD/YYYY', verbose_name='Start Date')),
                ('toDate', models.DateTimeField(help_text='MM/DD/YYYY', verbose_name='End Date')),
                ('timings', models.CharField(help_text='Timings for the event', max_length=255, verbose_name='Event Timings')),
                ('ticket', models.FloatField(help_text='Price for the event', null=True, verbose_name='Ticket Price')),
                ('isApproved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('createdBy', models.CharField(max_length=255, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_1', models.CharField(max_length=34)),
                ('choice_2', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='UserOpinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(max_length=255)),
                ('answers_1', models.CharField(max_length=255)),
                ('answers_2', models.CharField(max_length=255)),
                ('opinion', models.TextField(default='Test Opinion')),
                ('username', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
