<<<<<<< HEAD
# Generated by Django 3.1.4 on 2020-12-10 07:33
=======
# Generated by Django 3.1.3 on 2020-12-12 19:56
>>>>>>> 625c1ea148453707970a921ece247a254dc5a506

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Contribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload', models.ImageField(upload_to='contribute/uploads')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
=======
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255, unique=True, verbose_name='Event Name')),
                ('eventDesc', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Event Description')),
                ('fromDate', models.DateTimeField(auto_now_add=True, verbose_name='From Date')),
                ('toDate', models.DateTimeField(auto_now_add=True, verbose_name='To Date')),
                ('timings', models.CharField(max_length=255, null=True, verbose_name='Timings')),
                ('ticket', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ticket Price')),
                ('isApproved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('createdBy', models.CharField(max_length=255, verbose_name='Created By')),
>>>>>>> 625c1ea148453707970a921ece247a254dc5a506
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
