# Generated by Django 3.1.3 on 2020-12-14 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0002_auto_20201214_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timings',
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='fromDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='toDate',
            field=models.DateField(),
        ),
    ]
