# Generated by Django 3.1.4 on 2020-12-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0002_auto_20201210_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_1', models.CharField(max_length=34)),
                ('choice_2', models.CharField(max_length=34)),
                ('options', models.CharField(choices=[(models.CharField(max_length=34), models.CharField(max_length=34)), (models.CharField(max_length=34), models.CharField(max_length=34))], max_length=34)),
            ],
        ),
    ]
