# Generated by Django 3.1.4 on 2020-12-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0003_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
    ]
