# Generated by Django 3.1.3 on 2020-12-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0003_auto_20201213_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('eventID', models.IntegerField()),
                ('ticketPrice', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='createdBy',
            field=models.CharField(editable=False, max_length=255, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventDesc',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=255, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket',
            field=models.FloatField(null=True, verbose_name='Ticket Price'),
        ),
    ]
