# Generated by Django 3.1.4 on 2020-12-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0004_remove_poll_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(max_length=255)),
                ('answers_1', models.CharField(max_length=255)),
                ('answers_2', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
