# Generated by Django 3.1.3 on 2020-12-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0004_auto_20201213_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eventName',
            field=models.CharField(default='Christmas Eve 2020 Gettogether', max_length=255),
        ),
    ]
