# Generated by Django 3.1.4 on 2020-12-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0005_useropinions'),
    ]

    operations = [
        migrations.AddField(
            model_name='useropinions',
            name='opinion',
            field=models.TextField(default='Test Poll'),
            preserve_default=False,
        ),
    ]
