# Generated by Django 3.1.3 on 2020-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0006_auto_20201214_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ifPaid',
            field=models.BooleanField(default=False),
        ),
    ]
