# Generated by Django 3.1.4 on 2020-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maggotty', '0006_useropinions_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useropinions',
            name='opinion',
            field=models.TextField(default='Test Opinion'),
        ),
    ]
