"""
Django settings for web_project project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
settings_dir = os.path.dirname(__file__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

# Settings for email
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = 'maggottyhighalumni@gmail.com' 
EMAIL_HOST_PASSWORD = 'maggotty123$'
EMAIL_PORT = 587
REGISTRATION_EMAIL_BODY = '''<html><head>
	<title></title>
	<link href="https://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/css/wsc.css" rel="stylesheet" type="text/css" />
</head>
<body>
<p><span style="font-family:arial,helvetica,sans-serif">Congratulations ! You have successfully registered for the Maggotty High Alumni website.<br />
&nbsp;<br />
You now have unlimited access to all of this and more&hellip;<br />
&nbsp;</span></p>

<ul>
	<li>
	<p><span style="font-family:arial,helvetica,sans-serif">Create events to meet your fellow classmates</span></p>
	</li>
	<li>
	<p><span style="font-family:arial,helvetica,sans-serif">Register for upcoming events happening near you</span></p>
	</li>
	<li>
	<p><span style="font-family:arial,helvetica,sans-serif">Make donations and help your alma mater</span></p>
	</li>
	<li>
	<p><span style="font-family:arial,helvetica,sans-serif">Upload stories, pictures and more&hellip;</span></p>
	</li>
</ul>

<p><span style="font-family:arial,helvetica,sans-serif">&nbsp;<br />
Check out the <a href="http://localhost:8000/home/">Maggotty High Alumni website</a> and sign into your account.<br />
&nbsp;<br />
Regards,<br />
Maggotty High Alumni Association<br />
Contact us: <a href="mailto:maggottyhighalumni@gmail.com">maggottyhighalumni@gmail.com</a></span></p>
</body>
</html>'''

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ppy^v@pa&0^5a&y9gk!yi4q6llhn=w^8dw6*l^-&(y4gti@du$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Maggotty',
    'crispy_forms',
    'widget_tweaks',
    'tempus_dominus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['%s/templates/' % (PROJECT_DIR), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Maggotty.context_processors.get_current_cart_to_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CRISPY_TEMPLATE_PACK = 'bootstrap4'
LOGIN_URL = '/login'
LOGOUT_URL = '/logout'
LOGIN_REDIRECT_URL = '/home'
PROJECT_ROOT = os.path.abspath(os.path.dirname(settings_dir))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = ''
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    # this assumes your static contents is in <your_project>/static/
    os.path.join(BASE_DIR, 'static'),
)



# media files to be uploaded
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


